"""add_gear_status_column

Revision ID: 13573f0a8473
Revises: 7a8b9c0d1e2f
Create Date: 2026-03-23 17:33:40.689333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13573f0a8473'
down_revision: Union[str, Sequence[str], None] = '7a8b9c0d1e2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop existing type if it was partially created in previous failed run
    op.execute("DROP TYPE IF EXISTS gearstatusenum")
    
    # Create the enum type with correct values
    gear_status_enum = sa.Enum('Active', 'In Repair', 'Sold', 'Archived', name='gearstatusenum')
    gear_status_enum.create(op.get_bind(), checkfirst=False)
    
    op.add_column('user_cameras', sa.Column('status', gear_status_enum, server_default=sa.text("'Active'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_cameras', 'status')
    # ### end Alembic commands ###
