"""Initial migration

Revision ID: 532927a5f35c
Revises: 
Create Date: 2026-03-10 22:13:06.140553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '532927a5f35c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cameras',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('camera_type', sa.Enum('slr', 'tlr', 'rangefinder', 'point_shoot', 'view_camera', name='cameratypeenum'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('best_practice', sa.String(), nullable=True),
    sa.Column('image_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('film_stocks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('iso', sa.Integer(), nullable=False),
    sa.Column('format', sa.Enum('format_135', 'format_120', 'format_large', name='formatenum'), nullable=False),
    sa.Column('color_type', sa.Enum('color_negative', 'b_w', 'slide', name='colortypeenum'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('best_practice', sa.String(), nullable=True),
    sa.Column('image_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user_cameras',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('camera_id', sa.UUID(), nullable=True),
    sa.Column('rating_functional', sa.Integer(), nullable=True),
    sa.Column('rating_view', sa.Integer(), nullable=True),
    sa.Column('rating_looking', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rolls',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('film_stock_id', sa.UUID(), nullable=True),
    sa.Column('user_camera_id', sa.UUID(), nullable=True),
    sa.Column('shot_at_iso', sa.Integer(), nullable=True),
    sa.Column('expired_year', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('shooting', 'finished', 'at_lab', 'result_received', name='rollstatusenum'), server_default='shooting', nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=True),
    sa.ForeignKeyConstraint(['film_stock_id'], ['film_stocks.id'], ),
    sa.ForeignKeyConstraint(['user_camera_id'], ['user_cameras.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('images',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('roll_id', sa.UUID(), nullable=True),
    sa.Column('frame_number', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('aperture', sa.Float(), nullable=True),
    sa.Column('shutter_speed', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['roll_id'], ['rolls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    op.drop_table('rolls')
    op.drop_table('user_cameras')
    op.drop_table('users')
    op.drop_table('film_stocks')
    op.drop_table('cameras')
    # ### end Alembic commands ###
