"""add is_scan_sync to storage_credential

Revision ID: f5921b4a1449
Revises: 661b5699484b
Create Date: 2026-03-22 09:44:49.676427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5921b4a1449'
down_revision: Union[str, Sequence[str], None] = '661b5699484b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lenses', 'focal_length',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('rolls', 'max_frames',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('36'))
    op.create_foreign_key(None, 'rolls', 'user_lenses', ['user_lens_id'], ['id'])
    op.add_column('storage_credentials', sa.Column('is_scan_sync', sa.Boolean(), server_default=sa.text('FALSE'), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('storage_credentials', 'is_scan_sync')
    op.drop_constraint(None, 'rolls', type_='foreignkey')
    op.alter_column('rolls', 'max_frames',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('36'))
    op.alter_column('lenses', 'focal_length',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###
