// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB78444k9k-0JOTcSC2iIllpa26i3G9fLQ',
    appId: '1:413280765346:ios:9c36be0af7015cfbc49efb',
    messagingSenderId: '413280765346',
    projectId: 'halide-ae374',
    storageBucket: 'halide-ae374.firebasestorage.app',
    iosBundleId: 'com.halide.halidemanagement',
    iosClientId: '413280765346-2pq8udmspnct62nvojgpuafku9pq8som.apps.googleusercontent.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUjFL0ofEI9iBXkg_kPQf7-v284lsDsxg',
    appId: '1:413280765346:android:3e667aeaa450f02fc49efb',
    messagingSenderId: '413280765346',
    projectId: 'halide-ae374',
    storageBucket: 'halide-ae374.firebasestorage.app',
    androidClientId: '413280765346-3s5avvjccsgvarbr1luvc3s75ro7i631.apps.googleusercontent.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB78444k9k-0JOTcSC2iIllpa26i3G9fLQ',
    appId: '1:413280765346:ios:9c36be0af7015cfbc49efb',
    messagingSenderId: '413280765346',
    projectId: 'halide-ae374',
    storageBucket: 'halide-ae374.firebasestorage.app',
    iosBundleId: 'com.halide.halidemanagement',
    iosClientId: '413280765346-2pq8udmspnct62nvojgpuafku9pq8som.apps.googleusercontent.com',
  );
}
